In [3]:
import pandas as pd
data = pd.read_csv(r"C:\Users\kaila\Downloads\Amazon_sales.csv")
df = pd.DataFrame(data)
df.info()
df.head()
df.duplicated().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128975 entries, 0 to 128974
Data columns (total 22 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Order ID            128975 non-null  object
 1   Date                128975 non-null  object
 2   Status              128975 non-null  object
 3   Fulfilment          128975 non-null  object
 4   Sales Channel       128975 non-null  object
 5   ship-service-level  128975 non-null  object
 6   Style               128975 non-null  object
 7   SKU                 128975 non-null  object
 8   Category            128975 non-null  object
 9   Size                128975 non-null  object
 10  ASIN                128975 non-null  object
 11  Courier Status      122103 non-null  object
 12  Qty                 128975 non-null  int64
 13  currency            121180 non-null  object
 14  Amount              121180 non-null  float64
 15  ship-city           128942 non-null  object
 16  ship-state          128942 non-null  object
 17  ship-postal-code    128942 non-null  float64
 18  ship-country        128942 non-null  object
 19  promotion-ids       79822 non-null   object
 20  B2B                 128975 non-null  bool
 21  fulfilled-by        39277 non-null   object
dtypes: bool(1), float64(2), int64(1), object(18)
memory usage: 20.8+ MB

np.int64(6)

In [4]:
df.isnull().sum()

Order ID                  0
Date                      0
Status                    0
Fulfilment                0
Sales Channel             0
ship-service-level        0
Style                     0
SKU                       0
Category                  0
Size                      0
ASIN                      0
Courier Status         6872
Qty                       0
currency               7795
Amount                 7795
ship-city                33
ship-state               33
ship-postal-code         33
ship-country             33
promotion-ids         49153
B2B                       0
fulfilled-by          89698
dtype: int64

In [5]:
df["promotion-ids"].nunique()

5787

In [6]:
df["promotion-ids"].value_counts().head(10)

promotion-ids
IN Core Free Shipping 2015/04/08 23-48-5-108                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              46100
Duplicated A12RHGVGRWOT3S 1560498941486                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     489
Amazon PLCC Free-Financing Universal Merchant AAT-WNKTBO3K27EJC,Amazon PLCC Free-Financing Universal Merchant AAT-QX3UCCJESKPA2,Amazon PLCC Free-Financing Universal Merchant AAT-CXJHMC2YJUK76,Amazon PLCC Free-Financing Universal Merchant AAT-CC4FAVTYR4X7C,Amazon PLCC Free-Financing Universal Merchant AAT-XXRCW6NZEPZI4,Amazon PLCC Free-Financing Universal Merchant AAT-EOKPWFWYW7Y6I,Amazon PLCC Free-Financing Universal Merchant AAT-ZYL5UPUNW6T62,Amazon PLCC Free-Financing Universal Merchant AAT-G5ZRX4BZOIODU,Amazon PLCC Free-Financing Universal Merchant AAT-PZHUW6DZX4BPS,Amazon PLCC Free-Financing Universal Merchant AAT-XX7G3ZRJJJ5LG,Amazon PLCC Free-Financing Universal Merchant AAT-LEHCKNDBJG64E,Amazon PLCC Free-Financing Universal Merchant AAT-DJVHCEV7D7RQY,Amazon PLCC Free-Financing Universal Merchant AAT-BRSZZ45H6MHAO,Amazon PLCC Free-Financing Universal Merchant AAT-MKLXOOZWQL7GO,Amazon PLCC Free-Financing Universal Merchant AAT-CB7UNXEXGIJTC,Amazon PLCC Free-Financing Universal Merchant #MP-gzasho-1593152694811,Amazon PLCC Free-Financing Universal Merchant AAT-WLBA4GZ52EAH4                                                                                                                                                                                                                                                                                                                                      458
Duplicated AYTJSBA8ZOP16 1567159860988                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      433
Amazon PLCC Free-Financing Universal Merchant AAT-WNKTBO3K27EJC,Amazon PLCC Free-Financing Universal Merchant AAT-QX3UCCJESKPA2,Amazon PLCC Free-Financing Universal Merchant AAT-5QQ7BIYYQEDN2,Amazon PLCC Free-Financing Universal Merchant AAT-DSJ2QRXXWXVMQ,Amazon PLCC Free-Financing Universal Merchant AAT-CXJHMC2YJUK76,Amazon PLCC Free-Financing Universal Merchant AAT-CC4FAVTYR4X7C,Amazon PLCC Free-Financing Universal Merchant AAT-XXRCW6NZEPZI4,Amazon PLCC Free-Financing Universal Merchant AAT-EOKPWFWYW7Y6I,Amazon PLCC Free-Financing Universal Merchant AAT-ZYL5UPUNW6T62,Amazon PLCC Free-Financing Universal Merchant AAT-G5ZRX4BZOIODU,Amazon PLCC Free-Financing Universal Merchant AAT-PZHUW6DZX4BPS,Amazon PLCC Free-Financing Universal Merchant AAT-ETXQ3XXWMRXBG,Amazon PLCC Free-Financing Universal Merchant AAT-BRSZZ45H6MHAO,Amazon PLCC Free-Financing Universal Merchant AAT-MKLXOOZWQL7GO,Amazon PLCC Free-Financing Universal Merchant AAT-CB7UNXEXGIJTC,Amazon PLCC Free-Financing Universal Merchant #MP-gzasho-1593152694811,Amazon PLCC Free-Financing Universal Merchant AAT-WLBA4GZ52EAH4                                                                                                                                                                                                                                                                                                                                      316
Amazon PLCC Free-Financing Universal Merchant AAT-WNKTBO3K27EJC,Amazon PLCC Free-Financing Universal Merchant AAT-QX3UCCJESKPA2,Amazon PLCC Free-Financing Universal Merchant AAT-CXJHMC2YJUK76,Amazon PLCC Free-Financing Universal Merchant AAT-CC4FAVTYR4X7C,Amazon PLCC Free-Financing Universal Merchant AAT-XXRCW6NZEPZI4,Amazon PLCC Free-Financing Universal Merchant AAT-EOKPWFWYW7Y6I,Amazon PLCC Free-Financing Universal Merchant AAT-ZYL5UPUNW6T62,Amazon PLCC Free-Financing Universal Merchant AAT-G5ZRX4BZOIODU,Amazon PLCC Free-Financing Universal Merchant AAT-PZHUW6DZX4BPS,Amazon PLCC Free-Financing Universal Merchant AAT-BRSZZ45H6MHAO,Amazon PLCC Free-Financing Universal Merchant AAT-MKLXOOZWQL7GO,Amazon PLCC Free-Financing Universal Merchant AAT-CB7UNXEXGIJTC,Amazon PLCC Free-Financing Universal Merchant #MP-gzasho-1593152694811,Amazon PLCC Free-Financing Universal Merchant AAT-WLBA4GZ52EAH4                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      305
Amazon PLCC Free-Financing Universal Merchant AAT-WNKTBO3K27EJC,Amazon PLCC Free-Financing Universal Merchant AAT-QX3UCCJESKPA2,Amazon PLCC Free-Financing Universal Merchant AAT-5QQ7BIYYQEDN2,Amazon PLCC Free-Financing Universal Merchant AAT-DSJ2QRXXWXVMQ,Amazon PLCC Free-Financing Universal Merchant AAT-CXJHMC2YJUK76,Amazon PLCC Free-Financing Universal Merchant AAT-CC4FAVTYR4X7C,Amazon PLCC Free-Financing Universal Merchant AAT-XXRCW6NZEPZI4,Amazon PLCC Free-Financing Universal Merchant AAT-EOKPWFWYW7Y6I,Amazon PLCC Free-Financing Universal Merchant AAT-ZYL5UPUNW6T62,Amazon PLCC Free-Financing Universal Merchant AAT-G5ZRX4BZOIODU,Amazon PLCC Free-Financing Universal Merchant AAT-PZHUW6DZX4BPS,Amazon PLCC Free-Financing Universal Merchant AAT-ETXQ3XXWMRXBG,Amazon PLCC Free-Financing Universal Merchant AAT-7X3XCTYG64VBE,Amazon PLCC Free-Financing Universal Merchant AAT-7CHGD3WTS3MHM,Amazon PLCC Free-Financing Universal Merchant AAT-26ZDKNME27X42,Amazon PLCC Free-Financing Universal Merchant AAT-4ZF5KN6E4LJK4,Amazon PLCC Free-Financing Universal Merchant AAT-7RCXIKUAX7DDY,Amazon PLCC Free-Financing Universal Merchant AAT-BRSZZ45H6MHAO,Amazon PLCC Free-Financing Universal Merchant AAT-MKLXOOZWQL7GO,Amazon PLCC Free-Financing Universal Merchant AAT-CB7UNXEXGIJTC,Amazon PLCC Free-Financing Universal Merchant #MP-gzasho-1593152694811,Amazon PLCC Free-Financing Universal Merchant AAT-WLBA4GZ52EAH4      230
Amazon PLCC Free-Financing Universal Merchant AAT-WNKTBO3K27EJC,Amazon PLCC Free-Financing Universal Merchant AAT-QX3UCCJESKPA2,Amazon PLCC Free-Financing Universal Merchant AAT-5QQ7BIYYQEDN2,Amazon PLCC Free-Financing Universal Merchant AAT-DSJ2QRXXWXVMQ,Amazon PLCC Free-Financing Universal Merchant AAT-CXJHMC2YJUK76,Amazon PLCC Free-Financing Universal Merchant AAT-CC4FAVTYR4X7C,Amazon PLCC Free-Financing Universal Merchant AAT-FYWJCQHU2XQ2U,Amazon PLCC Free-Financing Universal Merchant AAT-EOKPWFWYW7Y6I,Amazon PLCC Free-Financing Universal Merchant AAT-URPEBMPS7TSPE,Amazon PLCC Free-Financing Universal Merchant AAT-5ZEB2OGNZ32MC,Amazon PLCC Free-Financing Universal Merchant AAT-YZ2VQO2YM6YYM,Amazon PLCC Free-Financing Universal Merchant AAT-4EOBCMLXMLDGY,Amazon PLCC Free-Financing Universal Merchant AAT-UB6CYNTOQMM7C,Amazon PLCC Free-Financing Universal Merchant AAT-BRSZZ45H6MHAO,Amazon PLCC Free-Financing Universal Merchant AAT-MKLXOOZWQL7GO,Amazon PLCC Free-Financing Universal Merchant AAT-CB7UNXEXGIJTC,Amazon PLCC Free-Financing Universal Merchant #MP-gzasho-1593152694811,Amazon PLCC Free-Financing Universal Merchant AAT-WLBA4GZ52EAH4                                                                                                                                                                                                                                                                      206
Amazon PLCC Free-Financing Universal Merchant AAT-WNKTBO3K27EJC,Amazon PLCC Free-Financing Universal Merchant AAT-QX3UCCJESKPA2,Amazon PLCC Free-Financing Universal Merchant AAT-CXJHMC2YJUK76,Amazon PLCC Free-Financing Universal Merchant AAT-CC4FAVTYR4X7C,Amazon PLCC Free-Financing Universal Merchant AAT-XXRCW6NZEPZI4,Amazon PLCC Free-Financing Universal Merchant AAT-EOKPWFWYW7Y6I,Amazon PLCC Free-Financing Universal Merchant AAT-ZYL5UPUNW6T62,Amazon PLCC Free-Financing Universal Merchant AAT-G5ZRX4BZOIODU,Amazon PLCC Free-Financing Universal Merchant AAT-YFJA6XMAMWZSK,Amazon PLCC Free-Financing Universal Merchant AAT-K66BSCE2J2V5E,Amazon PLCC Free-Financing Universal Merchant AAT-275LMAQ3T5REI,Amazon PLCC Free-Financing Universal Merchant AAT-BRSZZ45H6MHAO,Amazon PLCC Free-Financing Universal Merchant AAT-MKLXOOZWQL7GO,Amazon PLCC Free-Financing Universal Merchant AAT-CB7UNXEXGIJTC,Amazon PLCC Free-Financing Universal Merchant #MP-gzasho-1593152694811,Amazon PLCC Free-Financing Universal Merchant AAT-WLBA4GZ52EAH4                                                                                                                                                                                                                                                                                                                                                                                                      201
Amazon PLCC Free-Financing Universal Merchant AAT-WNKTBO3K27EJC,Amazon PLCC Free-Financing Universal Merchant AAT-QX3UCCJESKPA2,Amazon PLCC Free-Financing Universal Merchant AAT-5QQ7BIYYQEDN2,Amazon PLCC Free-Financing Universal Merchant AAT-DSJ2QRXXWXVMQ,Amazon PLCC Free-Financing Universal Merchant AAT-CXJHMC2YJUK76,Amazon PLCC Free-Financing Universal Merchant AAT-CC4FAVTYR4X7C,Amazon PLCC Free-Financing Universal Merchant AAT-FYWJCQHU2XQ2U,Amazon PLCC Free-Financing Universal Merchant AAT-EOKPWFWYW7Y6I,Amazon PLCC Free-Financing Universal Merchant AAT-URPEBMPS7TSPE,Amazon PLCC Free-Financing Universal Merchant AAT-YZ2VQO2YM6YYM,Amazon PLCC Free-Financing Universal Merchant AAT-4EOBCMLXMLDGY,Amazon PLCC Free-Financing Universal Merchant AAT-UB6CYNTOQMM7C,Amazon PLCC Free-Financing Universal Merchant AAT-BRSZZ45H6MHAO,Amazon PLCC Free-Financing Universal Merchant AAT-MKLXOOZWQL7GO,Amazon PLCC Free-Financing Universal Merchant AAT-CB7UNXEXGIJTC,Amazon PLCC Free-Financing Universal Merchant #MP-gzasho-1593152694811,Amazon PLCC Free-Financing Universal Merchant AAT-WLBA4GZ52EAH4                                                                                                                                                                                                                                                                                                                                      198
Name: count, dtype: int64

In [7]:
print(df.head())

              Order ID      Date                        Status Fulfilment  \
0  405-8078784-5731545  04-30-22                     Cancelled   Merchant
1  171-9198151-1101146  04-30-22  Shipped - Delivered to Buyer   Merchant
2  404-0687676-7273146  04-30-22                       Shipped     Amazon
3  403-9615377-8133951  04-30-22                     Cancelled   Merchant
4  407-1069790-7240320  04-30-22                       Shipped     Amazon

  Sales Channel  ship-service-level    Style              SKU       Category  \
0      Amazon.in           Standard   SET389   SET389-KR-NP-S            Set
1      Amazon.in           Standard  JNE3781  JNE3781-KR-XXXL          kurta
2      Amazon.in          Expedited  JNE3371    JNE3371-KR-XL          kurta
3      Amazon.in           Standard    J0341       J0341-DR-L  Western Dress
4      Amazon.in          Expedited  JNE3671  JNE3671-TU-XXXL            Top

  Size  ... Qty currency  Amount    ship-city   ship-state ship-postal-code  \
0    S  ...   0      INR  647.62       MUMBAI  MAHARASHTRA         400081.0
1  3XL  ...   1      INR  406.00    BENGALURU    KARNATAKA         560085.0
2   XL  ...   1      INR  329.00  NAVI MUMBAI  MAHARASHTRA         410210.0
3    L  ...   0      INR  753.33   PUDUCHERRY   PUDUCHERRY         605008.0
4  3XL  ...   1      INR  574.00      CHENNAI   TAMIL NADU         600073.0

  ship-country                                      promotion-ids    B2B  \
0           IN                                                NaN  False
1           IN  Amazon PLCC Free-Financing Universal Merchant ...  False
2           IN       IN Core Free Shipping 2015/04/08 23-48-5-108   True
3           IN                                                NaN  False
4           IN                                                NaN  False

  fulfilled-by
0    Easy Ship
1    Easy Ship
2          NaN
3    Easy Ship
4          NaN

[5 rows x 22 columns]

In [8]:
print(df.tail)

<bound method NDFrame.tail of                    Order ID      Date                        Status  \
0       405-8078784-5731545  04-30-22                     Cancelled
1       171-9198151-1101146  04-30-22  Shipped - Delivered to Buyer
2       404-0687676-7273146  04-30-22                       Shipped
3       403-9615377-8133951  04-30-22                     Cancelled
4       407-1069790-7240320  04-30-22                       Shipped
...                     ...       ...                           ...
128970  406-6001380-7673107  05-31-22                       Shipped
128971  402-9551604-7544318  05-31-22                       Shipped
128972  407-9547469-3152358  05-31-22                       Shipped
128973  402-6184140-0545956  05-31-22                       Shipped
128974  408-7436540-8728312  05-31-22                       Shipped

       Fulfilment Sales Channel  ship-service-level    Style              SKU  \
0        Merchant      Amazon.in           Standard   SET389   SET389-KR-NP-S
1        Merchant      Amazon.in           Standard  JNE3781  JNE3781-KR-XXXL
2          Amazon      Amazon.in          Expedited  JNE3371    JNE3371-KR-XL
3        Merchant      Amazon.in           Standard    J0341       J0341-DR-L
4          Amazon      Amazon.in          Expedited  JNE3671  JNE3671-TU-XXXL
...           ...            ...                ...      ...              ...
128970     Amazon      Amazon.in          Expedited  JNE3697    JNE3697-KR-XL
128971     Amazon      Amazon.in          Expedited   SET401   SET401-KR-NP-M
128972     Amazon      Amazon.in          Expedited    J0157     J0157-DR-XXL
128973     Amazon      Amazon.in          Expedited    J0012     J0012-SKD-XS
128974     Amazon      Amazon.in          Expedited    J0003      J0003-SET-S

             Category Size  ... Qty currency   Amount    ship-city  \
0                 Set    S  ...   0      INR   647.62       MUMBAI
1               kurta  3XL  ...   1      INR   406.00    BENGALURU
2               kurta   XL  ...   1      INR   329.00  NAVI MUMBAI
3       Western Dress    L  ...   0      INR   753.33   PUDUCHERRY
4                 Top  3XL  ...   1      INR   574.00      CHENNAI
...               ...  ...  ...  ..      ...      ...          ...
128970          kurta   XL  ...   1      INR   517.00    HYDERABAD
128971            Set    M  ...   1      INR   999.00     GURUGRAM
128972  Western Dress  XXL  ...   1      INR   690.00    HYDERABAD
128973            Set   XS  ...   1      INR  1199.00        Halol
128974            Set    S  ...   1      INR   696.00       Raipur

          ship-state ship-postal-code ship-country  \
0        MAHARASHTRA         400081.0           IN
1          KARNATAKA         560085.0           IN
2        MAHARASHTRA         410210.0           IN
3         PUDUCHERRY         605008.0           IN
4         TAMIL NADU         600073.0           IN
...              ...              ...          ...
128970     TELANGANA         500013.0           IN
128971       HARYANA         122004.0           IN
128972     TELANGANA         500049.0           IN
128973       Gujarat         389350.0           IN
128974  CHHATTISGARH         492014.0           IN

                                            promotion-ids    B2B fulfilled-by
0                                                     NaN  False    Easy Ship
1       Amazon PLCC Free-Financing Universal Merchant ...  False    Easy Ship
2            IN Core Free Shipping 2015/04/08 23-48-5-108   True          NaN
3                                                     NaN  False    Easy Ship
4                                                     NaN  False          NaN
...                                                   ...    ...          ...
128970                                                NaN  False          NaN
128971       IN Core Free Shipping 2015/04/08 23-48-5-108  False          NaN
128972                                                NaN  False          NaN
128973       IN Core Free Shipping 2015/04/08 23-48-5-108  False          NaN
128974       IN Core Free Shipping 2015/04/08 23-48-5-108  False          NaN

[128975 rows x 22 columns]>

In [9]:
print(df.columns)

Index(['Order ID', 'Date', 'Status', 'Fulfilment', 'Sales Channel ',
       'ship-service-level', 'Style', 'SKU', 'Category', 'Size', 'ASIN',
       'Courier Status', 'Qty', 'currency', 'Amount', 'ship-city',
       'ship-state', 'ship-postal-code', 'ship-country', 'promotion-ids',
       'B2B', 'fulfilled-by'],
      dtype='object')

In [10]:
df.drop(columns=['currency'])

,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,Size,...,Courier Status,Qty,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by
0,405-8078784-5731545,04-30-22,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,S,...,NaN,0,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,NaN,False,Easy Ship
1,171-9198151-1101146,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,3XL,...,Shipped,1,406.00,BENGALURU,KARNATAKA,560085.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship
2,404-0687676-7273146,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,XL,...,Shipped,1,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,True,NaN
3,403-9615377-8133951,04-30-22,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,L,...,NaN,0,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,NaN,False,Easy Ship
4,407-1069790-7240320,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,3XL,...,Shipped,1,574.00,CHENNAI,TAMIL NADU,600073.0,IN,NaN,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128970,406-6001380-7673107,05-31-22,Shipped,Amazon,Amazon.in,Expedited,JNE3697,JNE3697-KR-XL,kurta,XL,...,Shipped,1,517.00,HYDERABAD,TELANGANA,500013.0,IN,NaN,False,NaN
128971,402-9551604-7544318,05-31-22,Shipped,Amazon,Amazon.in,Expedited,SET401,SET401-KR-NP-M,Set,M,...,Shipped,1,999.00,GURUGRAM,HARYANA,122004.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN
128972,407-9547469-3152358,05-31-22,Shipped,Amazon,Amazon.in,Expedited,J0157,J0157-DR-XXL,Western Dress,XXL,...,Shipped,1,690.00,HYDERABAD,TELANGANA,500049.0,IN,NaN,False,NaN
128973,402-6184140-0545956,05-31-22,Shipped,Amazon,Amazon.in,Expedited,J0012,J0012-SKD-XS,Set,XS,...,Shipped,1,1199.00,Halol,Gujarat,389350.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN
128974,408-7436540-8728312,05-31-22,Shipped,Amazon,Amazon.in,Expedited,J0003,J0003-SET-S,Set,S,...,Shipped,1,696.00,Raipur,CHHATTISGARH,492014.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN

In [11]:
df['Amount']=df['Amount'].fillna(0)

In [12]:
df.isnull().sum()

Order ID                  0
Date                      0
Status                    0
Fulfilment                0
Sales Channel             0
ship-service-level        0
Style                     0
SKU                       0
Category                  0
Size                      0
ASIN                      0
Courier Status         6872
Qty                       0
currency               7795
Amount                    0
ship-city                33
ship-state               33
ship-postal-code         33
ship-country             33
promotion-ids         49153
B2B                       0
fulfilled-by          89698
dtype: int64

In [13]:
df['ship-city']=df['ship-city'].fillna('unknown')
df['ship-state']=df['ship-state'].fillna('unknown')
df['ship-postal-code']=df['ship-postal-code'].fillna('unknown')
df['ship-country']=df['ship-country'].fillna('unknown')
df.isnull().sum()

Order ID                  0
Date                      0
Status                    0
Fulfilment                0
Sales Channel             0
ship-service-level        0
Style                     0
SKU                       0
Category                  0
Size                      0
ASIN                      0
Courier Status         6872
Qty                       0
currency               7795
Amount                    0
ship-city                 0
ship-state                0
ship-postal-code          0
ship-country              0
promotion-ids         49153
B2B                       0
fulfilled-by          89698
dtype: int64

In [14]:
df['currency'].value_counts(dropna=False)

currency
INR    121180
NaN      7795
Name: count, dtype: int64

In [15]:
df['fulfilled-by'].value_counts(dropna=False)

fulfilled-by
NaN          89698
Easy Ship    39277
Name: count, dtype: int64

In [16]:
df['Courier Status'].value_counts(dropna=False)

Courier Status
Shipped      109487
NaN            6872
Unshipped      6681
Cancelled      5935
Name: count, dtype: int64

In [17]:
df[df['Courier Status'].isnull()]['Status'].value_counts()

Status
Cancelled                       6861
Shipped - Delivered to Buyer       8
Shipped - Returned to Seller       3
Name: count, dtype: int64

In [18]:
df['promotion_used']=df['promotion-ids'].notna()

In [19]:
df['Courier Status']= df['Courier Status'].fillna('unknown')

In [20]:
df.isnull().sum()

Order ID                  0
Date                      0
Status                    0
Fulfilment                0
Sales Channel             0
ship-service-level        0
Style                     0
SKU                       0
Category                  0
Size                      0
ASIN                      0
Courier Status            0
Qty                       0
currency               7795
Amount                    0
ship-city                 0
ship-state                0
ship-postal-code          0
ship-country              0
promotion-ids         49153
B2B                       0
fulfilled-by          89698
promotion_used            0
dtype: int64

In [21]:
df['currency']= df['currency'].fillna('INR')
df.isnull().sum()

Order ID                  0
Date                      0
Status                    0
Fulfilment                0
Sales Channel             0
ship-service-level        0
Style                     0
SKU                       0
Category                  0
Size                      0
ASIN                      0
Courier Status            0
Qty                       0
currency                  0
Amount                    0
ship-city                 0
ship-state                0
ship-postal-code          0
ship-country              0
promotion-ids         49153
B2B                       0
fulfilled-by          89698
promotion_used            0
dtype: int64

In [22]:
df['Date']= pd.to_datetime(df['Date'])
df['Month']= df['Date'].dt.month_name()
df['Year'] =df['Date'].dt.year

C:\Users\kaila\AppData\Local\Temp\ipykernel_1340\1149922065.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Date']= pd.to_datetime(df['Date'])

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128975 entries, 0 to 128974
Data columns (total 25 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Order ID            128975 non-null  object
 1   Date                128975 non-null  datetime64[ns]
 2   Status              128975 non-null  object
 3   Fulfilment          128975 non-null  object
 4   Sales Channel       128975 non-null  object
 5   ship-service-level  128975 non-null  object
 6   Style               128975 non-null  object
 7   SKU                 128975 non-null  object
 8   Category            128975 non-null  object
 9   Size                128975 non-null  object
 10  ASIN                128975 non-null  object
 11  Courier Status      128975 non-null  object
 12  Qty                 128975 non-null  int64
 13  currency            128975 non-null  object
 14  Amount              128975 non-null  float64
 15  ship-city           128975 non-null  object
 16  ship-state          128975 non-null  object
 17  ship-postal-code    128975 non-null  object
 18  ship-country        128975 non-null  object
 19  promotion-ids       79822 non-null   object
 20  B2B                 128975 non-null  bool
 21  fulfilled-by        39277 non-null   object
 22  promotion_used      128975 non-null  bool
 23  Month               128975 non-null  object
 24  Year                128975 non-null  int32
dtypes: bool(2), datetime64[ns](1), float64(1), int32(1), int64(1), object(19)
memory usage: 22.4+ MB

In [39]:
df.groupby('Category')['Amount'].sum().sort_values(ascending=False)

Category
Set              39204124.03
kurta            21299546.70
Western Dress    11216072.69
Top               5347792.30
Ethnic Dress       791217.66
Blouse             458408.18
Bottom             150667.98
Saree              123933.76
Dupatta               915.00
Name: Amount, dtype: float64

In [40]:
df.groupby('ship-state')['Amount'].sum().sort_values(ascending=False)

ship-state
MAHARASHTRA      13335534.14
KARNATAKA        10481114.37
TELANGANA         6916615.65
UTTAR PRADESH     6816642.08
TAMIL NADU        6515650.11
                    ...
rajsthan              521.00
AR                    493.00
Rajsthan              443.00
PB                    399.00
APO                     0.00
Name: Amount, Length: 70, dtype: float64

In [41]:
df['ship-state'].value_counts(dropna=False)

ship-state
MAHARASHTRA      22260
KARNATAKA        17326
TAMIL NADU       11483
TELANGANA        11330
UTTAR PRADESH    10638
                 ...
Puducherry           1
APO                  1
PB                   1
orissa               1
AR                   1
Name: count, Length: 70, dtype: int64

In [42]:
sorted(df['ship-state'].unique())

['ANDAMAN & NICOBAR ',
 'ANDHRA PRADESH',
 'APO',
 'AR',
 'ARUNACHAL PRADESH',
 'ASSAM',
 'Arunachal Pradesh',
 'Arunachal pradesh',
 'BIHAR',
 'Bihar',
 'CHANDIGARH',
 'CHHATTISGARH',
 'Chandigarh',
 'DADRA AND NAGAR',
 'DELHI',
 'Delhi',
 'GOA',
 'Goa',
 'Gujarat',
 'HARYANA',
 'HIMACHAL PRADESH',
 'JAMMU & KASHMIR',
 'JHARKHAND',
 'KARNATAKA',
 'KERALA',
 'LADAKH',
 'LAKSHADWEEP',
 'MADHYA PRADESH',
 'MAHARASHTRA',
 'MANIPUR',
 'MEGHALAYA',
 'MIZORAM',
 'Manipur',
 'Meghalaya',
 'Mizoram',
 'NAGALAND',
 'NL',
 'Nagaland',
 'New Delhi',
 'ODISHA',
 'Odisha',
 'Orissa',
 'PB',
 'PUDUCHERRY',
 'PUNJAB',
 'Pondicherry',
 'Puducherry',
 'Punjab',
 'Punjab/Mohali/Zirakpur',
 'RAJASTHAN',
 'RJ',
 'Rajasthan',
 'Rajshthan',
 'Rajsthan',
 'SIKKIM',
 'Sikkim',
 'TAMIL NADU',
 'TELANGANA',
 'TRIPURA',
 'UTTAR PRADESH',
 'UTTARAKHAND',
 'WEST BENGAL',
 'bihar',
 'delhi',
 'goa',
 'orissa',
 'punjab',
 'rajasthan',
 'rajsthan',
 'unknown']

In [43]:
df['ship-state'] = df['ship-state'].str.strip().str.upper()

In [44]:
sorted(df['ship-state'].unique())

['ANDAMAN & NICOBAR',
 'ANDHRA PRADESH',
 'APO',
 'AR',
 'ARUNACHAL PRADESH',
 'ASSAM',
 'BIHAR',
 'CHANDIGARH',
 'CHHATTISGARH',
 'DADRA AND NAGAR',
 'DELHI',
 'GOA',
 'GUJARAT',
 'HARYANA',
 'HIMACHAL PRADESH',
 'JAMMU & KASHMIR',
 'JHARKHAND',
 'KARNATAKA',
 'KERALA',
 'LADAKH',
 'LAKSHADWEEP',
 'MADHYA PRADESH',
 'MAHARASHTRA',
 'MANIPUR',
 'MEGHALAYA',
 'MIZORAM',
 'NAGALAND',
 'NEW DELHI',
 'NL',
 'ODISHA',
 'ORISSA',
 'PB',
 'PONDICHERRY',
 'PUDUCHERRY',
 'PUNJAB',
 'PUNJAB/MOHALI/ZIRAKPUR',
 'RAJASTHAN',
 'RAJSHTHAN',
 'RAJSTHAN',
 'RJ',
 'SIKKIM',
 'TAMIL NADU',
 'TELANGANA',
 'TRIPURA',
 'UNKNOWN',
 'UTTAR PRADESH',
 'UTTARAKHAND',
 'WEST BENGAL']

In [45]:
df['ship-state']=df['ship-state'].replace({'AR':'ARUNACHAL PRADESH','RAJSHTHAN':'RAJASTHAN','RAJSTHAN':'RAJASTHAN','RJ':'RAJASTHAN','PB':'PUNJAB','PUNJAB/MOHALI/ZIRAKPUR':'PUNJAB','ORISSA':'ODISHA','PUDUCHERRY':'PONDICHERRY','NL':'NAGALAND'})

In [46]:
sorted(df['ship-state'].unique())

['ANDAMAN & NICOBAR',
 'ANDHRA PRADESH',
 'APO',
 'ARUNACHAL PRADESH',
 'ASSAM',
 'BIHAR',
 'CHANDIGARH',
 'CHHATTISGARH',
 'DADRA AND NAGAR',
 'DELHI',
 'GOA',
 'GUJARAT',
 'HARYANA',
 'HIMACHAL PRADESH',
 'JAMMU & KASHMIR',
 'JHARKHAND',
 'KARNATAKA',
 'KERALA',
 'LADAKH',
 'LAKSHADWEEP',
 'MADHYA PRADESH',
 'MAHARASHTRA',
 'MANIPUR',
 'MEGHALAYA',
 'MIZORAM',
 'NAGALAND',
 'NEW DELHI',
 'ODISHA',
 'PONDICHERRY',
 'PUNJAB',
 'RAJASTHAN',
 'SIKKIM',
 'TAMIL NADU',
 'TELANGANA',
 'TRIPURA',
 'UNKNOWN',
 'UTTAR PRADESH',
 'UTTARAKHAND',
 'WEST BENGAL']

In [47]:
df.groupby('ship-state')['Amount'].sum().sort_values(ascending=False)

ship-state
MAHARASHTRA          13335534.14
KARNATAKA            10481114.37
TELANGANA             6916615.65
UTTAR PRADESH         6816642.08
TAMIL NADU            6515650.11
DELHI                 4346412.46
KERALA                3830227.58
WEST BENGAL           3507880.44
ANDHRA PRADESH        3219831.72
HARYANA               2882092.99
GUJARAT               2728651.82
RAJASTHAN             1761131.16
MADHYA PRADESH        1592382.98
BIHAR                 1415613.32
ODISHA                1386372.39
PUNJAB                1211666.84
ASSAM                 1018136.20
UTTARAKHAND            974143.55
JHARKHAND              919088.21
GOA                    637685.85
CHHATTISGARH           570485.83
HIMACHAL PRADESH       503364.51
JAMMU & KASHMIR        456932.74
MANIPUR                213981.99
CHANDIGARH             211740.67
PONDICHERRY            192573.24
ANDAMAN & NICOBAR      158723.62
NAGALAND               145055.67
SIKKIM                 140828.66
MEGHALAYA              119871.81
ARUNACHAL PRADESH       98265.00
TRIPURA                 92548.40
NEW DELHI               47109.95
DADRA AND NAGAR         42138.92
MIZORAM                 41948.71
LADAKH                  38388.43
UNKNOWN                 18671.00
LAKSHADWEEP              3175.29
APO                         0.00
Name: Amount, dtype: float64

In [49]:
df.to_csv('C:\\Users\\kaila\\OneDrive\\Documents\\webscrapproject\\amazon_sales.csv',index=False)

In [69]:
table2=pd.read_csv(r"C:\Users\kaila\Downloads\Sale Report.csv")
df = pd.DataFrame(table2)

In [70]:
print(df)
df.columns

      index       SKU Code Design No.  Stock       Category Size Color
0         0    AN201-RED-L      AN201    5.0  AN : LEGGINGS    L   Red
1         1    AN201-RED-M      AN201    5.0  AN : LEGGINGS    M   Red
2         2    AN201-RED-S      AN201    3.0  AN : LEGGINGS    S   Red
3         3   AN201-RED-XL      AN201    6.0  AN : LEGGINGS   XL   Red
4         4  AN201-RED-XXL      AN201    3.0  AN : LEGGINGS  XXL   Red
...     ...            ...        ...    ...            ...  ...   ...
9266   9266            NaN        NaN    NaN            NaN  NaN   NaN
9267   9267            NaN        NaN    NaN            NaN  NaN   NaN
9268   9268            NaN        NaN    NaN            NaN  NaN   NaN
9269   9269            NaN        NaN    NaN            NaN  NaN   NaN
9270   9270            NaN        NaN    NaN            NaN  NaN   NaN

[9271 rows x 7 columns]

Index(['index', 'SKU Code', 'Design No.', 'Stock', 'Category', 'Size',
       'Color'],
      dtype='object')

In [71]:
df.drop(columns=['index'])

           SKU Code Design No.  Stock       Category Size Color
0       AN201-RED-L      AN201    5.0  AN : LEGGINGS    L   Red
1       AN201-RED-M      AN201    5.0  AN : LEGGINGS    M   Red
2       AN201-RED-S      AN201    3.0  AN : LEGGINGS    S   Red
3      AN201-RED-XL      AN201    6.0  AN : LEGGINGS   XL   Red
4     AN201-RED-XXL      AN201    3.0  AN : LEGGINGS  XXL   Red
...             ...        ...    ...            ...  ...   ...
9266            NaN        NaN    NaN            NaN  NaN   NaN
9267            NaN        NaN    NaN            NaN  NaN   NaN
9268            NaN        NaN    NaN            NaN  NaN   NaN
9269            NaN        NaN    NaN            NaN  NaN   NaN
9270            NaN        NaN    NaN            NaN  NaN   NaN

[9271 rows x 6 columns]

In [72]:
df.isnull().sum()

index          0
SKU Code      83
Design No.    36
Stock         36
Category      45
Size          36
Color         45
dtype: int64

In [75]:
df = df.dropna(how='all')

In [76]:
df.isnull().sum()

index          0
SKU Code      83
Design No.    36
Stock         36
Category      45
Size          36
Color         45
dtype: int64

In [77]:
df[df['SKU Code'].isnull()].head(10)

     index SKU Code Design No.  Stock       Category  Size       Color
135    135      NaN      BL086    1.0         BLOUSE  FREE        Blue
142    142      NaN      BL087    0.0         BLOUSE  FREE  Multicolor
197    197      NaN      BL097    1.0         BLOUSE  XXXL      Maroon
198    198      NaN      BL098    2.0         BLOUSE  FREE       Brown
223    223      NaN      BL102    1.0         BLOUSE  FREE   Navy Blue
248    248      NaN      BL109    2.0         BLOUSE  FREE        Gold
273    273      NaN      BL113    0.0         BLOUSE  XXXL      Maroon
546    546      NaN      CH203    0.0  AN : LEGGINGS  FREE      Maroon
901    901      NaN      J0055    0.0            NaN     S         NaN
902    902      NaN      J0055    0.0            NaN    XL         NaN

In [78]:
df= df.dropna(subset=['SKU Code'])

In [79]:
df.isnull().sum()

index         0
SKU Code      0
Design No.    0
Stock         0
Category      0
Size          0
Color         0
dtype: int64

In [80]:
df.duplicated().sum()

np.int64(0)

In [81]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9188 entries, 0 to 9234
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   index       9188 non-null   int64
 1   SKU Code    9188 non-null   object
 2   Design No.  9188 non-null   object
 3   Stock       9188 non-null   float64
 4   Category    9188 non-null   object
 5   Size        9188 non-null   object
 6   Color       9188 non-null   object
dtypes: float64(1), int64(1), object(5)
memory usage: 574.2+ KB

In [82]:
df.to_csv('C:\\Users\\kaila\\OneDrive\\Documents\\webscrapproject\\sales.csv',index=False)